# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{fluxx_engine}
  s.version = "0.0.6"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Eric Hansen"]
  s.date = %q{2010-09-16}
  s.email = %q{fluxx@acesfconsulting.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.DASHBOARD.textile",
    "README.textile"
  ]
  s.files = [
    "app/controllers/client_stores_controller.rb",
    "app/controllers/realtime_updates_controller.rb",
    "app/models/client_store.rb",
    "app/models/multi_element_choice.rb",
    "app/models/multi_element_group.rb",
    "app/models/multi_element_value.rb",
    "app/models/realtime_update.rb",
    "app/views/client_stores/_client_store_show.html.haml",
    "app/views/insta/_card_settings.html.haml",
    "app/views/insta/_simple_footer.html.haml",
    "app/views/insta/edit.html.haml",
    "app/views/insta/filter.html.haml",
    "app/views/insta/index.html.haml",
    "app/views/insta/new.html.haml",
    "app/views/insta/show.html.haml",
    "app/views/insta/show/_contact_info.html.haml",
    "config/routes.rb",
    "lib/extensions/action_controller/base.rb",
    "lib/extensions/action_controller/controller_dsl.rb",
    "lib/extensions/action_controller/controller_dsl_create.rb",
    "lib/extensions/action_controller/controller_dsl_delete.rb",
    "lib/extensions/action_controller/controller_dsl_edit.rb",
    "lib/extensions/action_controller/controller_dsl_index.rb",
    "lib/extensions/action_controller/controller_dsl_new.rb",
    "lib/extensions/action_controller/controller_dsl_related.rb",
    "lib/extensions/action_controller/controller_dsl_show.rb",
    "lib/extensions/action_controller/controller_dsl_update.rb",
    "lib/extensions/action_controller/model_stub.rb",
    "lib/extensions/action_view/base.rb",
    "lib/extensions/active_record/base.rb",
    "lib/extensions/active_record/model_dsl.rb",
    "lib/extensions/active_record/model_dsl_export.rb",
    "lib/extensions/active_record/model_dsl_lock.rb",
    "lib/extensions/active_record/model_dsl_multi_element.rb",
    "lib/extensions/active_record/model_dsl_realtime.rb",
    "lib/extensions/active_record/model_dsl_search.rb",
    "lib/extensions/active_record/model_dsl_utc.rb",
    "lib/extensions/array_extension.rb",
    "lib/extensions/blob_struct.rb",
    "lib/extensions/file.rb",
    "lib/extensions/fixnum_extensions.rb",
    "lib/extensions/formtastic_override.rb",
    "lib/extensions/inflections.rb",
    "lib/extensions/time_formats.rb",
    "lib/extensions/url_cleaner.rb",
    "lib/fluxx_engine.rb",
    "lib/fluxx_engine/engine.rb",
    "lib/generators/fluxx_engine_locale/fluxx_engine_locale_generator.rb",
    "lib/generators/fluxx_engine_locale/templates/en.yml",
    "lib/generators/fluxx_engine_migration/fluxx_engine_migration_generator.rb",
    "lib/generators/fluxx_engine_migration/templates/create_client_stores.rb",
    "lib/generators/fluxx_engine_migration/templates/create_multi_element_choices.rb",
    "lib/generators/fluxx_engine_migration/templates/create_multi_element_groups.rb",
    "lib/generators/fluxx_engine_migration/templates/create_multi_element_values.rb",
    "lib/generators/fluxx_engine_migration/templates/realtime_updates.rb",
    "lib/generators/fluxx_engine_public/fluxx_engine_public_generator.rb"
  ]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Fluxx Engine}
  s.test_files = [
    "test/blueprint.rb",
    "test/dummy/app/controllers/application_controller.rb",
    "test/dummy/app/controllers/instruments_controller.rb",
    "test/dummy/app/controllers/musicians_controller.rb",
    "test/dummy/app/helpers/application_helper.rb",
    "test/dummy/app/helpers/instruments_helper.rb",
    "test/dummy/app/helpers/musicians_helper.rb",
    "test/dummy/app/models/instrument.rb",
    "test/dummy/app/models/musician.rb",
    "test/dummy/app/models/musician_instrument.rb",
    "test/dummy/app/models/orchestra.rb",
    "test/dummy/app/models/user.rb",
    "test/dummy/config/application.rb",
    "test/dummy/config/boot.rb",
    "test/dummy/config/environment.rb",
    "test/dummy/config/environments/development.rb",
    "test/dummy/config/environments/production.rb",
    "test/dummy/config/environments/test.rb",
    "test/dummy/config/initializers/backtrace_silencers.rb",
    "test/dummy/config/initializers/inflections.rb",
    "test/dummy/config/initializers/mime_types.rb",
    "test/dummy/config/initializers/secret_token.rb",
    "test/dummy/config/initializers/session_store.rb",
    "test/dummy/config/routes.rb",
    "test/dummy/db/migrate/20100616232433_create_musicians.rb",
    "test/dummy/db/migrate/20100622221457_create_instruments.rb",
    "test/dummy/db/migrate/20100628185658_create_musician_instruments.rb",
    "test/dummy/db/migrate/20100628231219_fluxx_engine_create_realtime_updates_table.rb",
    "test/dummy/db/migrate/20100630001541_fluxx_engine_create_multi_element_groups.rb",
    "test/dummy/db/migrate/20100630001543_fluxx_engine_create_multi_element_values.rb",
    "test/dummy/db/migrate/20100630001545_fluxx_engine_create_multi_element_choices.rb",
    "test/dummy/db/migrate/20100702184319_create_orchestras.rb",
    "test/dummy/db/migrate/20100707235002_acts_as_audited_migration.rb",
    "test/dummy/db/migrate/20100709130327_fluxx_engine_create_client_stores.rb",
    "test/dummy/db/migrate/20100714054627_create_users.rb",
    "test/dummy/db/schema.rb",
    "test/dummy/db/seeds.rb",
    "test/fluxx_engine_test.rb",
    "test/functional/client_stores_controller_test.rb",
    "test/functional/instrument_controller_test.rb",
    "test/functional/musician_controller_test.rb",
    "test/functional/realtime_updates_controller_test.rb",
    "test/integration/navigation_test.rb",
    "test/support/integration_case.rb",
    "test/test_helper.rb",
    "test/unit/active_record/model_dsl_export_test.rb",
    "test/unit/active_record/model_dsl_lock_test.rb",
    "test/unit/active_record/model_dsl_multi_element_test.rb",
    "test/unit/active_record/model_dsl_realtime_test.rb",
    "test/unit/active_record/model_dsl_search_test.rb",
    "test/unit/active_record/model_dsl_utc_test.rb",
    "test/unit/blob_struct_test.rb",
    "test/unit/controller/controller_dsl_create_test.rb",
    "test/unit/controller/controller_dsl_delete_test.rb",
    "test/unit/controller/controller_dsl_edit_test.rb",
    "test/unit/controller/controller_dsl_index_test.rb",
    "test/unit/controller/controller_dsl_new_test.rb",
    "test/unit/controller/controller_dsl_related_test.rb",
    "test/unit/controller/controller_dsl_show_test.rb",
    "test/unit/controller/controller_dsl_update_test.rb",
    "test/unit/extension/array_extension_test.rb",
    "test/unit/extension/fixnum_extension_test.rb",
    "test/unit/extension/inflections_test.rb",
    "test/unit/extension/time_format_test.rb",
    "test/unit/instrument_test.rb",
    "test/unit/musician_test.rb",
    "test/unit/orchestra_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, ["= 3.0.0"])
      s.add_runtime_dependency(%q<capybara>, ["= 0.3.7"])
      s.add_runtime_dependency(%q<sqlite3-ruby>, [">= 0"])
      s.add_runtime_dependency(%q<fastercsv>, [">= 1.5.3"])
      s.add_runtime_dependency(%q<formtastic>, ["~> 1.1.0"])
      s.add_runtime_dependency(%q<haml>, [">= 3"])
      s.add_runtime_dependency(%q<will_paginate>, ["~> 3.0.pre2"])
      s.add_runtime_dependency(%q<jsmin>, [">= 1.0.1"])
      s.add_runtime_dependency(%q<thin>, [">= 1.2.7"])
      s.add_runtime_dependency(%q<machinist>, [">= 1.0.6"])
      s.add_runtime_dependency(%q<faker>, [">= 0.3.1"])
      s.add_runtime_dependency(%q<rcov>, [">= 0"])
      s.add_runtime_dependency(%q<thinking-sphinx>, ["= 2.0.0.rc1"])
      s.add_runtime_dependency(%q<aasm>, ["= 2.2.0"])
      s.add_runtime_dependency(%q<acts_as_audited_rails3>, [">= 1.1.1.5"])
      s.add_runtime_dependency(%q<ruby-debug>, [">= 0.10.3"])
    else
      s.add_dependency(%q<rails>, ["= 3.0.0"])
      s.add_dependency(%q<capybara>, ["= 0.3.7"])
      s.add_dependency(%q<sqlite3-ruby>, [">= 0"])
      s.add_dependency(%q<fastercsv>, [">= 1.5.3"])
      s.add_dependency(%q<formtastic>, ["~> 1.1.0"])
      s.add_dependency(%q<haml>, [">= 3"])
      s.add_dependency(%q<will_paginate>, ["~> 3.0.pre2"])
      s.add_dependency(%q<jsmin>, [">= 1.0.1"])
      s.add_dependency(%q<thin>, [">= 1.2.7"])
      s.add_dependency(%q<machinist>, [">= 1.0.6"])
      s.add_dependency(%q<faker>, [">= 0.3.1"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<thinking-sphinx>, ["= 2.0.0.rc1"])
      s.add_dependency(%q<aasm>, ["= 2.2.0"])
      s.add_dependency(%q<acts_as_audited_rails3>, [">= 1.1.1.5"])
      s.add_dependency(%q<ruby-debug>, [">= 0.10.3"])
    end
  else
    s.add_dependency(%q<rails>, ["= 3.0.0"])
    s.add_dependency(%q<capybara>, ["= 0.3.7"])
    s.add_dependency(%q<sqlite3-ruby>, [">= 0"])
    s.add_dependency(%q<fastercsv>, [">= 1.5.3"])
    s.add_dependency(%q<formtastic>, ["~> 1.1.0"])
    s.add_dependency(%q<haml>, [">= 3"])
    s.add_dependency(%q<will_paginate>, ["~> 3.0.pre2"])
    s.add_dependency(%q<jsmin>, [">= 1.0.1"])
    s.add_dependency(%q<thin>, [">= 1.2.7"])
    s.add_dependency(%q<machinist>, [">= 1.0.6"])
    s.add_dependency(%q<faker>, [">= 0.3.1"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<thinking-sphinx>, ["= 2.0.0.rc1"])
    s.add_dependency(%q<aasm>, ["= 2.2.0"])
    s.add_dependency(%q<acts_as_audited_rails3>, [">= 1.1.1.5"])
    s.add_dependency(%q<ruby-debug>, [">= 0.10.3"])
  end
end

