require 'rubygems'
require 'jsmin'

SOURCES   = FileList['src/fluxx.{core,storage,poller,stage,card,dock,dashboard}.js']
LIBRARIES = FileList[
  'lib/jquery-ui-1/js/jquery-1.4.2.min.js',
  'lib/jquery-ui-1/js/jquery-ui-1.8.2.custom.min.js',
  'lib/*.js',
  'lib/plupload/plupload.full.min.js',
  'lib/plupload/jquery.plupload.queue.min.js',
  'lib/colorbox/jquery.colorbox.js',
  'lib/jquery.colorbox.alerts.js',
  'src/jquery.select_transfer.js'
]

SASS = FileList['theme/*/sass/*.sass']

def sass2css(source, destination)
  sh "sass --style compact #{source} #{destination}"
end

def compile_sources(sources)
  sources.map{ |src|
    File.open(src, 'r') {|f| f.read }
  }.join('')
end

def minify_source(source)
  minified = nil
  File.open(source, 'r') { |input|
    minified = JSMin.minify(input)
  }
  minified
end

directory 'dist'

rule '.css' do |t|
  destination = t.name
  source = destination.gsub(/css/, 'sass')
  $stderr.puts ">>> #{source} -> #{destination}"
  sass2css source, destination
end

file 'dist/fluxx.engine.js' => [SOURCES].flatten do |t|
  File.open(t.name, 'w') {|f| f.write(compile_sources t.prerequisites)}
end

file 'dist/fluxx.engine.full.js' => [LIBRARIES, 'dist/fluxx.engine.js'].flatten do |t|
  File.open(t.name, 'w') {|f| f.write(compile_sources t.prerequisites)}
end

file 'dist/fluxx.engine.min.js' => ['dist/fluxx.engine.js'] do |t|
  File.open(t.name, 'w') {|f| f.write(minify_source t.prerequisites.first)}
end

file 'dist/fluxx.engine.full.min.js' => ['dist/fluxx.engine.full.js'] do |t|
  File.open(t.name, 'w') {|f| f.write(minify_source t.prerequisites.first)}
end

namespace "server" do
  desc 'Start Fluxx Dashboard Development Server'
  task :start do
    `thin -p 2424 -s5 -R config.ru restart`
  end
  desc 'Stop Fluxx Dashboard Development Server'
  task :stop do
    `thin -p 2424 -s5 -R config.ru stop`
  end
end

desc "Open Fluxx Dashboard Tests"
task :test => ['server:start'] do
  `open http://127.0.0.1:2424/test/index.html`
end

desc "Open Fluxx Dashboard Demo"
task :demo => ['server:start'] do
  `open http://127.0.0.1:2424/demo/wireframe.html`
end

desc 'Build All Sources'
task :build => ['build:js', 'build:css'] do
end

namespace "build" do
  desc 'Build JavaScript'
  task :js => ['dist', 'dist/fluxx.engine.min.js', 'dist/fluxx.engine.full.min.js'] do
    $stderr.puts ">>> Built JavaScript Sources"
  end
  
  desc 'Build Stylesheets'
  task :css, [:destination] do |t, args|
    if args.destination
      destination = args.destination
      source = destination.gsub(/css/, 'sass')
      if File.exist?(source)
        $stderr.puts ">>> #{source} -> #{destination}"
        sass2css source, destination
      end
    else
      SASS.each{ |source|
        destination = source.gsub(/sass/, 'css')
        if File.exist?(source)
          $stderr.puts ">>> #{source} -> #{destination}"
          sass2css source, destination
        end
      }
    end
  end
end

desc 'Clean All Sources'
task :clean do
  FileList['dist/*.js'].each{
    |f| File.delete(f)
  }
end


